version: '3.4'

services:
  portfolioapp:
    image: portfolioapp123.azurecr.io/portfolioapp:latest
    volumes:
      - mystorage:/app
    env_file:
      - .env
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
  redis:
    image: portfolioapp123.azurecr.io/redis:alpine
  celery:
    image: portfolioapp123.azurecr.io/celery:latest
    volumes:
      - mystorage:/app
    command: celery -A backend worker -l info
    env_file:
      - .env
    depends_on:
      - redis
      - portfolioapp
  celery-beat:
    image: portfolioapp123.azurecr.io/celery-beat:latest
    volumes:
      - mystorage:/app
    command: celery -A backend beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    env_file:
      - .env
    depends_on:
      - redis
      - portfolioapp
