version: '3.4'

services:
  portfolioapp:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: portfolioapp123.azurecr.io/portfolioapp
    volumes:
      - mydata:/mount/testvolumes
    env_file:
      - .env
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
  celery:
    build: .
    image: portfolioapp123.azurecr.io/celery
    command: celery -A backend worker --beat --scheduler django --loglevel=info
    volumes:
      - mydata:/mount/testvolumes
    env_file:
      - .env
    depends_on:
      - portfolioapp
      - redis
  redis:
    image: "redis:alpine"

volumes:
  mydata:
    driver: azure_file
    driver_opts:
      share_name: acishare
      storage_account_name: mystorageaccount30693
