version: "3.8"

services:
  portfolioapp:
    build: .
    container_name: portfolioapp
    env_file:
      - .env
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - pgdb
      - redis
  pgdb:
    image: postgres
    container_name: pgdb
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: "redis:alpine"
  celery:
    build: .
    container_name: celery
    env_file:
      - .env
    command: celery -A backend worker -l info
    depends_on:
      - redis
      - portfolioapp
  celery-beat:
    build: .
    image: celery-beat
    env_file:
      - .env
    command: celery -A backend beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      - redis
      - portfolioapp
volumes:
  pgdata:
