version: '3.4'

services:
  portfolioapp:
    image: portfolioapp
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app/
    env_file:
      - .env
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
  celery:
    build: .
    command: celery -A backend worker --beat --scheduler django --loglevel=info
    volumes:
      - .:/app/
    env_file:
      - .env
    depends_on:
      - portfolioapp
      - redis
  redis:
    image: "redis:alpine"
